name: exemplo-basico

on:
    pull_request:
        branches:
            - main

jobs:
    check-application:
        runs-on: ubuntu-20.04
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-python@v5
              with:
                python-version: '3.10'
            - run: python testes.py -v

