name: exemplo-basico

on:
    pull_request:
        branches:
            - master

jobs:
    check-application:
        runs-on: ubuntu-20.04
        strategy:
            matrix:
                python: ['3.10','3.11']
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-python@v5
              with:
                python-version: ${{ matrix.python }}
            - run: python testes.py -v

